require("plugins.conf.black-nvim")
require("plugins.conf.fzf-lua")
require("plugins.conf.gitsigns")
require("plugins.conf.lualine")
require("plugins.conf.LuaSnip")
require("plugins.conf.nvim-autopairs")
require("plugins.conf.nvim-cmp")
require("plugins.conf.nvim-colorizer")
require("plugins.conf.nvim-lsp")
require("plugins.conf.nvim-tree")
require("plugins.conf.nvim-treesitter")
require("plugins.conf.onedark")
require("plugins.conf.SimplyFold")
require("plugins.conf.tabline")
require("plugins.conf.vim-tmux-navigator")

